### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by zero617** [Garulf/Github-Notifications#27]
Please type any relevant information here

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "D:\Software\scoop\apps\anaconda3\current\lib\site-packages\urllib3\connectionpool.py", line 692, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "D:\Software\scoop\apps\anaconda3\current\lib\site-packages\urllib3\connectionpool.py", line 281, in _get_conn
    return conn or self._new_conn()
  File "D:\Software\scoop\apps\anaconda3\current\lib\site-packages\urllib3\connectionpool.py", line 1009, in _new_conn
    raise SSLError(
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\scoop\apps\anaconda3\current\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "D:\Software\scoop\apps\anaconda3\current\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "D:\Software\scoop\apps\anaconda3\current\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /notifications?all=true (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\scoop\apps\flow-launcher\current\app-1.10.0\UserData\Plugins\Github Notifications-3.0.10\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
  File "D:\Software\scoop\apps\flow-launcher\current\app-1.10.0\UserData\Plugins\Github Notifications-3.0.10\lib\flox\__init__.py", line 131, in _query
    self.query(query)
  File "D:\Software\scoop\apps\flow-launcher\current\app-1.10.0\UserData\Plugins\Github Notifications-3.0.10\plugin\main.py", line 56, in query
    self._results = self.main_search()
  File "D:\Software\scoop\apps\flow-launcher\current\app-1.10.0\UserData\Plugins\Github Notifications-3.0.10\lib\flox\utils.py", line 41, in wrapper
    data = func(*args, **kwargs)
  File "D:\Software\scoop\apps\flow-launcher\current\app-1.10.0\UserData\Plugins\Github Notifications-3.0.10\plugin\main.py", line 32, in main_search
    for notification in notifications:
  File "D:\Software\scoop\apps\flow-launcher\current\app-1.10.0\UserData\Plugins\Github Notifications-3.0.10\lib\github\PaginatedList.py", line 82, in __iter__
    yield self.__list[index]
  File "D:\Software\scoop\apps\flow-launcher\current\app-1.10.0\UserData\Plugins\Github Notifications-3.0.10\lib\github\PaginatedList.py", line 48, in __getitem__
    self.__fetchToIndex(index)
  File "D:\Software\scoop\apps\flow-launcher\current\app-1.10.0\UserData\Plugins\Github Notifications-3.0.10\lib\github\PaginatedList.py", line 64, in __fetchToIndex
    self._grow()
  File "D:\Software\scoop\apps\flow-launcher\current\app-1.10.0\UserData\Plugins\Github Notifications-3.0.10\lib\github\PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "D:\Software\scoop\apps\flow-launcher\current\app-1.10.0\UserData\Plugins\Github Notifications-3.0.10\lib\github\PaginatedList.py", line 201, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "D:\Software\scoop\apps\flow-launcher\current\app-1.10.0\UserData\Plugins\Github Notifications-3.0.10\lib\github\Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "D:\Software\scoop\apps\flow-launcher\current\app-1.10.0\UserData\Plugins\Github Notifications-3.0.10\lib\github\Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "D:\Software\scoop\apps\flow-launcher\current\app-1.10.0\UserData\Plugins\Github Notifications-3.0.10\lib\github\Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "D:\Software\scoop\apps\flow-launcher\current\app-1.10.0\UserData\Plugins\Github Notifications-3.0.10\lib\github\Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "D:\Software\scoop\apps\flow-launcher\current\app-1.10.0\UserData\Plugins\Github Notifications-3.0.10\lib\github\Requester.py", line 127, in getresponse
    r = verb(
  File "D:\Software\scoop\apps\anaconda3\current\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "D:\Software\scoop\apps\anaconda3\current\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Software\scoop\apps\anaconda3\current\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "D:\Software\scoop\apps\anaconda3\current\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /notifications?all=true (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

```
</p>
</details>

**Comment by Garulf** [comment]
This may be an issue with the plugin and your locally installed requests package. Please try Flows embedded Python or pointing Flow at a Python 3.8 or higher installation.

**Comment by Garulf** [comment]
Please give this version a try and see if it fixes your issue.
https://github.com/Garulf/Github-Notifications/files/10263169/artifact.12.zip


You can install in Flow by typing:
```
pm install https://github.com/Garulf/Github-Notifications/files/10263169/artifact.12.zip
```

**Comment by zero617** [comment]
![image](https://user-images.githubusercontent.com/67105838/208835816-6792fe59-d668-424c-999e-0f18faf7a3dd.png)
still the same issue
