### ISSUE TITLE
Immediate error when typing the action keyword

### ISSUE THREAD

**Issue by heldheld** [Garulf/Github-Notifications#30]
Flow Launcher got an error

`
Please open new issue in: https://github.com/Garulf/github-notifications/issues/new
1. upload log file: C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Logs\1.11.0\2023-01-04.txt
2. copy below exception message

Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\Gebruiker\AppData\Local\Programs\Python\Python310\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 01/04/2023 17:08:24
Exception:
Github Notifications Exception: 
Websites: https://github.com/Garulf/github-notifications
Author: Garulf
Version: 3.0.11
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\run.py", line 9, in <module>
    from plugin.main import GithubNotifications
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\plugin\main.py", line 4, in <module>
    from github import Github
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\github\__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\github\MainClass.py", line 59, in <module>
    import github.Event
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\github\Event.py", line 32, in <module>
    import github.NamedUser
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\github\NamedUser.py", line 44, in <module>
    import github.Organization
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\github\Organization.py", line 50, in <module>
    import github.Repository
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\github\Repository.py", line 128, in <module>
    import github.PublicKey
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\github\PublicKey.py", line 34, in <module>
    from nacl import encoding, public
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\nacl\public.py", line 16, in <module>
    import nacl.bindings
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\nacl\bindings\__init__.py", line 16, in <module>
    from nacl.bindings.crypto_aead import (
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\nacl\bindings\crypto_aead.py", line 17, in <module>
    from nacl._sodium import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\run.py", line 9, in <module>
    from plugin.main import GithubNotifications
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\plugin\main.py", line 4, in <module>
    from github import Github
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\github\__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\github\MainClass.py", line 59, in <module>
    import github.Event
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\github\Event.py", line 32, in <module>
    import github.NamedUser
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\github\NamedUser.py", line 44, in <module>
    import github.Organization
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\github\Organization.py", line 50, in <module>
    import github.Repository
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\github\Repository.py", line 128, in <module>
    import github.PublicKey
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\github\PublicKey.py", line 34, in <module>
    from nacl import encoding, public
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\nacl\public.py", line 16, in <module>
    import nacl.bindings
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\nacl\bindings\__init__.py", line 16, in <module>
    from nacl.bindings.crypto_aead import (
  File "C:\Users\Gebruiker\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.11\lib\nacl\bindings\crypto_aead.py", line 17, in <module>
    from nacl._sodium import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 292
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 307
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 821
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 785
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

`

**Comment by Garulf** [comment]
I think I see the issue. Please try using Python 3.8 and see if your issue goes away.

**Comment by heldheld** [comment]
> I think I see the issue. Please try using Python 3.8 and see if your issue goes away.

Now it does work! So this plugin doesn't support later versions of Python?

**Comment by Garulf** [comment]
@Dultus your error looks to be some issue with Flow Launcher not being able to run Python. 

According to the logs the plugin was never even started. Please make sure Flow Launcher has the proper permissions to run Python. 

Alternatively you could try and let Flow use it's own embedded Python.
