### ISSUE TITLE
Error after adding typing `gn`

### ISSUE THREAD

**Issue by TheBestPessimist** [Garulf/Github-Notifications#36]
Steps:
1. install plugin
2. generate github token, paste into plugin config page
3. open FL and type `gn`

```
Please open new issue in: https://github.com/Garulf/github-notifications/issues/new
1. upload log file: D:\all\all\Flow.Launcher\app-1.14.0\UserData\Logs\1.14.0\2023-03-15.txt
2. copy below exception message

Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: D:\all\all\Python\Python 3.11.1\pythonw.exe
Node Path: 
Date: 03/15/2023 15:44:08
Exception:
Github Notifications Exception: 
Websites: https://github.com/Garulf/github-notifications
Author: Garulf
Version: 3.0.15
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "D:\all\all\Flow.Launcher\app-1.14.0\UserData\Plugins\Github Notifications-3.0.15\run.py", line 9, in <module>
    from plugin.main import GithubNotifications
  File "D:\all\all\Flow.Launcher\app-1.14.0\UserData\Plugins\Github Notifications-3.0.15\plugin\main.py", line 1, in <module>
    from flox import Flox, utils
  File "D:\all\all\Flow.Launcher\app-1.14.0\UserData\Plugins\Github Notifications-3.0.15\lib\flox\__init__.py", line 47, in <module>
    raise FileNotFoundError(LAUNCHER_NOT_FOUND_MSG)
FileNotFoundError: Unable to locate Launcher directory
Current working directory: D:\all\all\Flow.Launcher\app-1.14.0\UserData\Plugins\Github Notifications-3.0.15

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "D:\all\all\Flow.Launcher\app-1.14.0\UserData\Plugins\Github Notifications-3.0.15\run.py", line 9, in <module>
    from plugin.main import GithubNotifications
  File "D:\all\all\Flow.Launcher\app-1.14.0\UserData\Plugins\Github Notifications-3.0.15\plugin\main.py", line 1, in <module>
    from flox import Flox, utils
  File "D:\all\all\Flow.Launcher\app-1.14.0\UserData\Plugins\Github Notifications-3.0.15\lib\flox\__init__.py", line 47, in <module>
    raise FileNotFoundError(LAUNCHER_NOT_FOUND_MSG)
FileNotFoundError: Unable to locate Launcher directory
Current working directory: D:\all\all\Flow.Launcher\app-1.14.0\UserData\Plugins\Github Notifications-3.0.15

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 829
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 803
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
Log: [2023-03-15.txt](https://github.com/Garulf/Github-Notifications/files/10980481/2023-03-15.txt)

**Comment by Garulf** [comment]
Hello @TheBestPessimist , just wanted to let you know I see the issue and will push out a fix soon.

**Comment by Garulf** [comment]
I finally got a chance to sit down and look at this bug. The issue that is causing the crash is because my Flox library is looking for the Flow Launcher directory. 

It fails however because it doesn't expect a "." in the flow launcher directory name.

How was you Flow Launcher installed?

**Comment by TheBestPessimist** [comment]
I'm using portable FL.
