### ISSUE TITLE
Error while typing "gn"

### ISSUE THREAD

**Issue by davidp57** [Garulf/Github-Notifications#39]
Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: C:\Python311\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 04/09/2023 09:24:47
Exception:
Github Notifications Exception: 
Websites: https://github.com/Garulf/github-notifications
Author: Garulf
Version: 3.0.17
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Could not find platform independent libraries <prefix>
ModuleNotFoundError: No module named '_cffi_backend'
thread '<unnamed>' panicked at 'Python API call failed', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pyo3-0.15.2\src\err\mod.rs:582:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\run.py", line 9, in <module>
    from plugin.main import GithubNotifications
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\plugin\main.py", line 4, in <module>
    from github import Github
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\Lib\github\__init__.py", line 58, in <module>
    from github.GithubIntegration import GithubIntegration
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\Lib\github\GithubIntegration.py", line 4, in <module>
    import jwt
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\Lib\jwt\__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\Lib\jwt\api_jwk.py", line 6, in <module>
    from .algorithms import get_default_algorithms
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\Lib\jwt\algorithms.py", line 6, in <module>
    from .utils import (
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\Lib\jwt\utils.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\Lib\cryptography\hazmat\primitives\asymmetric\ec.py", line 10, in <module>
    from cryptography.hazmat._oid import ObjectIdentifier
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\Lib\cryptography\hazmat\_oid.py", line 7, in <module>
    from cryptography.hazmat.bindings._rust import (
pyo3_runtime.PanicException: Python API call failed

 ---> System.IO.InvalidDataException: Could not find platform independent libraries <prefix>
ModuleNotFoundError: No module named '_cffi_backend'
thread '<unnamed>' panicked at 'Python API call failed', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pyo3-0.15.2\src\err\mod.rs:582:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\run.py", line 9, in <module>
    from plugin.main import GithubNotifications
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\plugin\main.py", line 4, in <module>
    from github import Github
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\Lib\github\__init__.py", line 58, in <module>
    from github.GithubIntegration import GithubIntegration
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\Lib\github\GithubIntegration.py", line 4, in <module>
    import jwt
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\Lib\jwt\__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\Lib\jwt\api_jwk.py", line 6, in <module>
    from .algorithms import get_default_algorithms
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\Lib\jwt\algorithms.py", line 6, in <module>
    from .utils import (
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\Lib\jwt\utils.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\Lib\cryptography\hazmat\primitives\asymmetric\ec.py", line 10, in <module>
    from cryptography.hazmat._oid import ObjectIdentifier
  File "C:\Users\dpier\AppData\Roaming\FlowLauncher\Plugins\Github Notifications-3.0.17\Lib\cryptography\hazmat\_oid.py", line 7, in <module>
    from cryptography.hazmat.bindings._rust import (
pyo3_runtime.PanicException: Python API call failed

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 803
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2023-04-09.txt](https://github.com/Garulf/Github-Notifications/files/11184979/2023-04-09.txt)

**Comment by Garulf** [comment]
Please use Python 3.8. Most plugins for Flow Launcher are made with this version as the target.

Sadly there is no easy way to support multiple versions of Python with some libraries that include compiled code.

**Comment by Sneakpeakcss** [comment]
> Please use Python 3.8. Most plugins for Flow Launcher are made with this version as the target.
> 
> Sadly there is no easy way to support multiple versions of Python with some libraries that include compiled code.

Seems like this error comes out of box now after Flows Python update to v3.11.4

**Comment by pfeerick** [comment]
Same here with Flow Launcher 1.16.2. It looks like `cffi` for both the OP and me. 

```
Python Path: C:\Users\pfeer\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 11/11/2023 18:34:33
Exception:
Github Notifications Exception: 
Websites: https://github.com/Garulf/github-notifications
Author: Garulf
Version: 4.0.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: ModuleNotFoundError: No module named '_cffi_backend'
```

**Comment by Garulf** [comment]
Yeah the requests library unfortunately uses compiled code. 

If this compiled code is packaged for one version of Python but run on a different one it reports missing imports.

**Comment by RedDaut** [comment]
I have solved this issue as outlined here: https://github.com/Garulf/Github-Notifications/issues/53#issuecomment-1959045643
